VERSION 0.7
PROJECT sonrhq/testnet-1
FROM earthly/earthly:v0.7.23
RUN apk add --no-cache bash curl nodejs npm && curl -1sLf \
    'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
        && apk add infisical

# build - builds the ipfs binary
build:
    FROM ipfs/kubo:latest
    COPY ./scripts/init-ipfs.sh config.sh
    EXPOSE 8080 4001 5001 8081
    SAVE IMAGE --push ghcr.io/sonrhq/ipfs:latest sonrhq/ipfs:latest ipfs-runner:latest
