VERSION 0.7
PROJECT sonrhq/rails


# build - builds the indexer binary
build:
    FROM ghcr.io/defiantlabs/cosmos-indexer:main
    WORKDIR /indexer
    COPY start.sh .
    ENTRYPOINT ["sh", "start.sh"]
    SAVE IMAGE sonrhq/indexer:latest
