project_name: sonr-rpc
builds:
  - binary: sonr-rpc
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: sonr-io
    name: core
