version: "3"

vars:
  GOPATH:
    sh: go env GOPATH
  BIN_DIR: "{{.GOPATH}}/bin"
  OS:
    sh: uname -s
  ARCH:
    sh: uname -m

tasks:
  hway:build:
    silent: true
    cmds: 
      - gum spin --spinner dot --title "Build Hway Single Target ({{.OS}}/{{.ARCH}})..." -- goreleaser build --snapshot --clean --single-target --id hway -o {{.BIN_DIR}}/hway

  sonrd:build:
    silent: true
    cmds: 
      - gum spin --spinner dot --title "Build Sonrd Single Target ({{.OS}}/{{.ARCH}})..." -- make build
      - gum spin --spinner dot --title "Moving Binary to $GOBIN..." -- mv build/sonrd {{.BIN_DIR}}/sonrd
      - rm -rf build

