# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: sonr
builds:
  - id: sonr
    main: ./cmd/snrd
    binary: snrd
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=snrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
    tags:
      - netgo
      - ledger

archives:
  - id: sonr
    name_template: >-
      sonr_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: ["tar.gz"]
    files:
      - src: README*
    wrap_in_directory: true

nfpms:
  - id: sonr
    package_name: snrd
    file_name_template: "sonr_{{ .Os }}_{{ .Arch }}{{ .ConventionalExtension }}"
    vendor: Sonr
    homepage: "https://sonr.io"
    maintainer: "Sonr <support@sonr.io>"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    license: "Apache 2.0"
    formats:
      - rpm
      - deb
      - apk
    dependencies:
      - ipfs
    contents:
      - src: README*
        dst: /usr/share/doc/snrd
    bindir: /usr/bin
    section: net
    priority: optional
    # Add these lines to match build config

brews:
  - name: snrd
    ids: [sonr]
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    caveats: "Run a local sonr node and access it with the hway proxy"
    homepage: "https://onsonr.dev"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    dependencies:
      - name: ipfs
    repository:
      owner: sonr-io
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"

release:
  github:
    owner: sonr-io
    name: snrd
  name_template: "{{ .Tag }}"
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: ./README*
    - glob: ./scripts/install.sh
    - glob: ./scripts/test_node.sh
    - glob: ./scripts/test_ics_node.sh

announce:
  telegram:
    enabled: true
    chat_id: -1002222617755
