# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: sonr

builds:
  - id: motr
    main: ./cmd/motr
    binary: app
    goos:
      - js
    goarch:
      - wasm
    
  - id: sonr
    main: ./cmd/sonrd
    binary: sonrd
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
    tags:
      - netgo
      - ledger

  - id: hway
    main: ./cmd/hway
    binary: hway
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -mod=readonly
      - -trimpath
    goamd64:
      - v1
    tags:
      - netgo
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
archives:
  - id: sonr
    builds: [sonr]
    name_template: >-
      sonr_{{ .Version }}_
      {{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - src: README*
    wrap_in_directory: true

  - id: hway
    builds: [hway]
    name_template: >-
      hway_{{ .Version }}_
      {{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - src: README*
    wrap_in_directory: true

nfpms:
  - id: hway
    package_name: hway
    file_name_template: "{{ .ConventionalFileName }}"
    builds: [hway]
    vendor: Sonr
    homepage: "https://onsonr.dev"
    maintainer: "Sonr <support@onsonr.dev>"
    description: "Sonr Highway is a decentralized, permissionless, and censorship-resistant identity network proxy."
    license: "Apache 2.0"
    formats:
      - rpm
      - deb
      - apk
    dependencies:
      - ipfs
    contents:
      - src: README*
        dst: /usr/share/doc/hway
    bindir: /usr/bin
    section: net
    priority: optional
    # Add these lines to match build config

  - id: sonr
    package_name: sonrd
    file_name_template: "{{ .ConventionalFileName }}"
    builds: [sonr]
    vendor: Sonr
    homepage: "https://onsonr.dev"
    maintainer: "Sonr <support@onsonr.dev>"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    license: "Apache 2.0"
    formats:
      - rpm
      - deb
      - apk
    dependencies:
      - ipfs
    contents:
      - src: README*
        dst: /usr/share/doc/sonrd
    bindir: /usr/bin
    section: net
    priority: optional
    # Add these lines to match build config

brews:
  - name: hway
    ids: [hway]
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    caveats: "Run a local hway node and access it with the hway proxy"
    homepage: "https://onsonr.dev"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    dependencies:
      - name: ipfs
    repository:
      owner: onsonr
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"

  - name: sonr
    ids: [sonr]
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    caveats: "Run a local sonr node and access it with the hway proxy"
    homepage: "https://onsonr.dev"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    dependencies:
      - name: ipfs
    repository:
      owner: onsonr
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"

release:
  github:
    owner: onsonr
    name: sonr
  name_template: "Release {{.Version}}"
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: ./README*

announce:
  telegram:
    enabled: true
    chat_id: -1002222617755
