# Project information.
project_name: sonrd
release:
  github:
    owner: sonrhq
    name: core

# The prebuild section.
before:
  hooks:
    - go mod download
    - go mod verify
    - go mod tidy
    - go generate ./...

# The builds section.
builds:
  - id: "sonrd"
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags:
      - -ldflags=-w -s -extldflags "-static" -X github.com/cosmos/cosmos-sdk/version.Name=sonr -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
    env:
      - CGO_ENABLED=0

# The archives section.
archives:
  - id: "sonrd"
    builds:
      - sonrd
    format: tar.gz
    files:
      - LICENSE*
      - README.md
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

# The checksum section.
checksum:
  name_template: 'checksums.txt'

# The snapcraft section.
kos:
-
  id: sonrd
  build: sonrd
  main: ./cmd/sonrd
  working_dir: .
  base_image: alpine
  labels:
    org.opencontainers.image.created: '{{ .Date }}'
    org.opencontainers.image.title: '{{ .ProjectName }}'
    org.opencontainers.image.version: '{{ .Tag }}'
    org.opencontainers.image.source: 'https://github.com/sonrhq/core'
  repository: ghcr.io/sonrhq/sonrd
  platforms:
  - linux/amd64
  - linux/arm64
  tags:
  - latest
  - '{{ .Tag }}'
  sbom: none
  bare: true
brews:
  -
    commit_author:
      name: goreleaserbot
      email: bot@sonr.io
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: "Start using with `sonrd help` command."
    homepage: "https://sonr.io/docs/"
    description: "Sonr is a peer-to-peer identity and asset management system that leverages DID documents, Webauthn, and IPFS — providing users with a secure, user-friendly way to manage their digital identity and assets."

    # SPDX identifier of your app's license.
    license: "Open GNU v3 License"
    repository:
      owner: sonrhq
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
