# Project information.
project_name: sonrd

env:
  - CGO_ENABLED=1
  - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download
  - COSMWASM_VERSION=v1.2.4
before:
  hooks:
    - go mod download

builds:
  # Build - Linux (amd64)
  - id: sonrd-linux-amd64
    env:
        - CC=x86_64-linux-gnu-gcc
    hooks:
      pre:
        - wget {{ .Env.WASMVM_URL }}/v1.2.4/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,muslc,osusergo
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - muslc
      - osusergo

  # Build - Linux (arm64)
  - id: sonrd-linux-arm64
    env:
        - CC=aarch64-linux-gnu-gcc
    hooks:
      pre:
        #- wget {{ .Env.WASMVM_URL }}/v1.2.4/libwasmvm_muslc.aarch64.a -O /lib/libwasmvm_muscl.a
        - wget {{ .Env.WASMVM_URL }}/v1.2.4/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,muslc,osusergo
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - muslc
      - ousergo
  # Build - Darwin (amd64)
  - id: sonrd-darwin-amd64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    hooks:
      pre:
        - wget {{ .Env.WASMVM_URL }}/v1.2.4/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - static_wasm
      - ledger

  # Build - Darwin (arm64)
  - id: sonrd-darwin-arm64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    hooks:
      pre:
        - wget {{ .Env.WASMVM_URL }}/v1.2.4/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - static_wasm
      - ledger

# ! ||--------------------------------------------------------------------------------||
# ! ||                                Tarball Archives                                ||
# ! ||--------------------------------------------------------------------------------||
universal_binaries:
  - id: sonrd-darwin-universal
    ids:
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    replace: false
archives:
  - id: zipped
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-amd64
      - sonrd-linux-arm64
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
  - id: binaries
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-arm64
      - sonrd-linux-amd64
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: binary
checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# ! ||--------------------------------------------------------------------------------||
# ! ||                              Release and Changelog                             ||
# ! ||--------------------------------------------------------------------------------||
release:
  github:
    owner: sonr-io
    name: sonr
  footer: |

    ## ⚡️ Binaries

    Binaries for Linux and Darwin (amd64 and arm64) are available below.
    Darwin users can also use the same universal binary `sonrd-{{ .Version }}-darwin-all` for both amd64 and arm64.

    ## 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/sonr-io/sonr
    cd core && git checkout v{{ .Version }}
    make install
    # Then run sonrd
    sonrd version
    # v{{ .Version }}
    ````

    ## 🐳 Run with Docker

    As an alternative to installing and running sonrd on your system, you may run sonrd in a Docker container.
    The following Docker images are available in our registry:

    | Image Name                               | Base                                 | Description                       | Registry Source                                     |
    |------------------------------------------|--------------------------------------|-----------------------------------|-----------------------------------------------------|
    | `sonr-io/sonrd:{{ .Version }}`            | `distroless/static-debian11`         | Default image based on Distroless | [ghcr.io/sonr-io/sonrd](https://ghcr.io/sonr-io/sonrd:latest) |
    | `sonr-io/sonrd:{{ .Version }}-standalone` | `distroless/static-debian11`         | Standalone testing node image     | [ghcr.io/sonr-io/sonrd-standalone](https://ghcr.io/sonr-io/sonrd:latest-standalone) |
    | `sonr-io/sonr-faucet:{{ .Version }}`      | `distroless/static-debian11`         | Development environment faucet    | [ghcr.io/sonr-io/sonr-faucet](https://ghcr.io/sonr-io/sonr-faucet:latest) |

    Example run:

    ```bash
    docker run sonr-io/sonrd:{{ .Version }} version
    # v{{ .Version }}
    ````

    All the images support `amd64` architectures.

  name_template: "Sonr Core - v{{.Version}} 🆔"
  mode: replace
  draft: true
changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: '.*?feat\(.*\):.*$'
      order: 0
    - title: "Documentation"
      regexp: '.*?docs\(.*\):.*$'
      order: 1
    - title: "Fixes"
      regexp: '.*?fix\(.*\):.*$'
      order: 2
    - title: "Chores"
      regexp: '.*?chore\(.*\):.*$'
      order: 3
    - title: Others
      order: 999
