# Sonr Build Pipeline
#
#

# -- Pre Release Hooks --
before:
  hooks:
    - go mod download

# -- Post Release Hooks --
after:
  hooks:
  - rm -rf ./SonrMotor.xcframework
  - rm -rf ./io.sonr.motor.aar
  - rm -rf ./sonr-motor.wasm
  - rm -rf ./dist
  - rm -rf ./build

# -- Individual Builds --
builds:
  # Motor Framework for Wasm
  - id: "motor-wasm"
    builder: prebuilt
    goos:
    - js
    - darwin
    goarch:
    - wasm
    - arm64
    prebuilt:
      path: build/motorlib-{{.OS}}-{{.Arch}}
    # UNCOMMENT THIS LINE TO DISABLE BUILD FOR WASM
    # skip: true
    hooks:
      pre:
        - task motor:bind

    # Highway Daemon for macOS
  - id: "highwayd-darwin"
    main: ./cmd/highwayd
    binary: highwayd
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
    - amd64
    - arm64

  # Highway Daemon for Linux
  - id: "highwayd-linux"
    main: ./cmd/highwayd
    binary: highwayd
    env:
      - CGO_ENABLED=0
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
    - amd64

  # Highway Daemon for Windows
  - id: "highwayd-windows"
    main: ./cmd/highwayd
    binary: highwayd
    env:
      - CGO_ENABLED=0
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe


  # Blockchain Daemon for macOS
  - id: "sonrd-darwin"
    main: ./cmd/sonrd
    binary: sonrd
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
        - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=sonr -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  # Blockchain Daemon for Linux
  - id: "sonrd-linux"
    main: ./cmd/sonrd
    binary: sonrd
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -X github.com/cosmos/cosmos-sdk/version.Name=sonr -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  # Blockchain Daemon for Windows
  - id: "sonrd-windows"
    main: ./cmd/sonrd
    binary: bin/sonrd
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=sonr -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

  # Highway CLI for macOS
  - id: "highway-cli-darwin"
    main: ./cmd/highway-cli
    binary: highway-cli
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
    - amd64
    - arm64

  # Highway CLI for Linux
  - id: "highway-cli-linux"
    main: ./cmd/highway-cli
    binary: highway-cli
    env:
      - CGO_ENABLED=0
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64


  # Highway CLI for Windows
  - id: "highway-cli-windows"
    main: ./cmd/highway-cli
    binary: highway-cli
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe


# -- Artifacts from the build --
archives:
# Templating for blockchain daemons
- id: "sonrd-archive"
  name_template: 'sonrd-{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macos
    windows: win
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  builds:
  - sonrd-darwin
  - sonrd-windows
  - sonrd-linux

# Templating for Motor Wasm
- id: "motor-wasm-archive"
  name_template: 'motorlib-{{ .Os }}_{{ .Arch }}'
  builds:
  - motor-bind
  files:
    - ./sonr-motor.wasm


# Templating for Motor Android
- id: "motor-android-archive"
  name_template: 'motorlib-{{ .Os }}_{{ .Arch }}'
  builds:
  - motor-bind
  files:
    - ./io.sonr.motor.aar

# Templating for Motor iOS
- id: "motor-ios-archive"
  name_template: 'motorlib-{{ .Os }}_{{ .Arch }}'
  builds:
  - motor-bind
  replacements:
    darwin: ios
  files:
    - ./SonrMotor.xcframework/


# Templating for CLI
- id: "highway-cli-archive"
  name_template: 'highway-cli-{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macos
    windows: win
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  builds:
  - highway-cli-darwin
  - highway-cli-linux
  - highway-cli-windows

  # Templating for Highway Daemon
- id: "highwayd-archive"
  name_template: 'highwayd-{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macos
    windows: win
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  builds:
  - highwayd-darwin
  - highwayd-linux
  - highwayd-windows

# -- Checksums for the archives --
checksum:
  name_template: 'checksums.txt'

# -- Changelog Configuration --
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# -- Snapshot of the current version --
snapshot:
  name_template: "{{ .Tag }}-next"

# -- Release settings --
release:
  github:
    owner: sonr-io
    name: sonr
  prerelease: auto
  discussion_category_name: General
  mode: append
  extra_files:
    - name_template: CHANGELOG.md
    - name_template: LICENSE
    - name_template: README.md
  # Header template for the release body.
  # Defaults to empty.
  header: |
    #### Release {{ .Tag }} - {{ .Date }}

    Welcome to the new {{ .Tag }} Sonr release. This release includes the following changes:


  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}! With much love from the [Sonr Team](https://sonr.io).

    #### Connect with us
    - [Discord](https://discord.gg/HSTPCzDUsW)
    - [Twitter](https://twitter.com/sonr_io)
    - [Documentation](https://docs.sonr.io)
