# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: sonr

before:
  hooks:
    - echo "Release date is {{ .Env.RELEASE_DATE }}"
    - docker build -t ghcr.io/onsonr/sonr:latest .
    - docker tag ghcr.io/onsonr/sonr:latest ghcr.io/onsonr/sonr:{{ .Tag }}
    - docker push ghcr.io/onsonr/sonr:{{ .Tag }}
    - docker push ghcr.io/onsonr/sonr:latest

builds:
  - id: sonr
    main: ./cmd/sonrd
    binary: sonrd
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
    tags:
      - netgo
      - ledger

archives:
  - id: sonr
    builds: [sonr]
    name_template: >-
      sonr_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - src: README*
    wrap_in_directory: true

nfpms:
  - id: sonr
    package_name: sonrd
    file_name_template: "sonrd_{{ .Os }}_{{ .Arch }}{{ .ConventionalExtension }}"
    builds: [sonr]
    vendor: Sonr
    homepage: "https://onsonr.dev"
    maintainer: "Sonr <support@onsonr.dev>"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    license: "Apache 2.0"
    formats:
      - rpm
      - deb
      - apk
    dependencies:
      - ipfs
    contents:
      - src: README*
        dst: /usr/share/doc/sonrd
    bindir: /usr/bin
    section: net
    priority: optional
    # Add these lines to match build config

brews:
  - name: sonr
    ids: [sonr]
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    caveats: "Run a local sonr node and access it with the hway proxy"
    homepage: "https://onson.dev"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    dependencies:
      - name: ipfs
    repository:
      owner: onsonr
      name: homebrew-tap
      branch: master
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"

release:
  github:
    owner: onsonr
    name: sonr
  name_template: "{{ .Tag }} | {{ .Env.RELEASE_DATE }}"
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: ./README*
    - glob: ./scripts/install.sh
    - glob: ./scripts/test_node.sh
    - glob: ./scripts/test_ics_node.sh

announce:
  telegram:
    enabled: true
    chat_id: -1002222617755
