version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "sh scripts/setup_ipfs.sh"
    background: true
    availability:
      restart: on_failure
      max_restarts: 0

  sonr:
    namespace: testnet
    command: "devbox run start:testnet"
    restart: on_failure
    env:
    max_restarts: 1
    depends:
      - ipfs
  #
  # tunnel:
  #   namespace: public
  #   command: "cloudflared tunnel run --token $TUNNEL_TOKEN"
  #   restart: on_failure
  #   max_restarts: 1
