version: "0.5"

processes:
  sonr:
    namespace: testnet
    command: "make dop-testnet"

  hway:
    namespace: testnet
    command: "./build/hway"

  ipfs:
    namespace: testnet
    command: "ipfs daemon"
