version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "sh scripts/setup_ipfs.sh"
    background: true
    availability:
      restart: never
      max_restarts: 0

  sonr:
    namespace: testnet
    background: true
    command: "make sh-testnet"
    restart: never
    max_restarts: 1
    depends:
      - ipfs
