version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "sh scripts/setup_ipfs.sh"
    background: true
    availability:
      restart: never
      max_restarts: 0

  sonr:
    namespace: testnet
    background: true
    command: "make sh-testnet"
    restart: never
    max_restarts: 1
    depends:
      - ipfs

  hway:
    namespace: public
    command: "task hway:dev"
    restart: on_failure
    max_restarts: 1
    depends:
      - ipfs

  tunnel:
    namespace: public
    enabled: false
    command: "#cloudflared tunnel run --token $TUNNEL_TOKEN"
    restart: on_failure
    max_restarts: 1
