version: "0.5"

processes:
  IPFS:
    namespace: testnet
    command: "ipfs daemon --mount"
    ready_log_line: "Daemon is ready"

  Sonr:
    namespace: testnet
    command: "task sonrd:start"
    depends_on:
      IPFS:
        condition: process_log_ready

  Hway:
    namespace: testnet
    command: "hway"
    depends_on:
      IPFS:
        condition: process_log_ready
      Sonr:
        condition: process_started
