version: "3"

vars:
  GREETING: Hello, World!

tasks:
  hway:build:
    cmds:
      - GOOS=js GOARCH=wasm go build -o ./cmd/hway/build/app.wasm ./cmd/hway/main.go

  hway:dev:
    dir: cmd/hway
    cmds:
      - bunx wrangler dev

  hway:deploy:
    dir: cmd/hway
    cmds:
      - bunx wrangler deploy

  motr:build:
    cmds:
      - GOOS=js GOARCH=wasm go build -o ./pkg/dwn/app.wasm ./cmd/motr/main.go

  nebula:build:
    dir: pkg/nebula
    cmds:
      - bun install
      - bun run deps.mjs
      - bunx tailwindcss -i ./global/styles/globals.css -o ./assets/css/styles.css
