version: "3"

vars:
  VERSION:
    sh: git describe --tags --abbrev=0
  COMMIT:
    sh: git rev-parse --short HEAD
  ROOT:
    sh: git rev-parse --show-toplevel
  OS:
    sh: uname -s
  TASKS:
    sh: task -l
  DOPPLER_TOKEN:
    sh: skate get DOPPLER_NETWORK

includes:
  pkl:
    taskfile: taskfiles/pkl.yml
    flatten: true
  psql:
    taskfile: taskfiles/psql.yml
    flatten: true
  ipfs:
    taskfile: taskfiles/ipfs.yml
    flatten: true
  sonr:
    taskfile: taskfiles/sonr.yml
    flatten: true
  svcs:
    taskfile: taskfiles/svcs.yml
    flatten: true

tasks:
  default:
    cmds:
      - gh run ls -L 3
      - gum format -- "# Sonr ({{.OS}}-{{.VERSION}})" " - ({{.COMMIT}}) {{.ROOT}}"
      - task -l -j | jq -r '.tasks[].name' | fzf --height=20 --reverse --header="Execute task:" --header-lines=1 | xargs task
    silent: true

  clean:
    internal: true
    cmds:
      - sh ./scripts/init_env.sh
      - rm -rf ./build
      - rm -rf ./dist
      - rm -rf ./static
    silent: true

