version: "3"

vars:
  VERSION:
    sh: git describe --tags --abbrev=0
  COMMIT:
    sh: git rev-parse --short HEAD
  ROOT:
    sh: git rev-parse --show-toplevel
  OS:
    sh: uname -s
  TASKS:
    sh: task -l
  DOPPLER_TOKEN:
    sh: skate get DOPPLER_NETWORK

includes:
  config:
    taskfile: .taskfiles/Config.yml
    flatten: true
  gen:
    taskfile: .taskfiles/Generate.yml
  init:
    taskfile: .taskfiles/Initialize.yml
  install:
    taskfile: .taskfiles/Install.yml
  serve:
    taskfile: .taskfiles/Serve.yml
    flatten: true

tasks:
  default:
    cmds:
      - gh run ls -L 3
      - gum format -- "# Sonr ({{.OS}}-{{.VERSION}})" " - ({{.COMMIT}}) {{.ROOT}}"
      - task -l -j | jq -r '.tasks[].name' | fzf --height=16 | xargs task
    silent: true
