version: "3"

includes:
  web:dashboard:
    taskfile: ./web/dashboard/Taskfile.yaml
    dir: web/dashboard
  web:wallet:
    taskfile: ./web/wallet/Taskfile.yaml
    dir: web/wallet

vars:
  VERSION: v0.0.1-test

tasks:
  bind:
    cmds:
      - echo "Binding Motor Node for all platforms"
      - sh ./scripts/bind.sh -i
      - sh ./scripts/bind.sh -a
      - sh ./scripts/bind.sh -w
  buf:
    cmds:
      - echo "Building Protobufs and pushing to registry"
      - task: buf:blockchain
      - task: buf:motor

  buf:motor:
    dir: internal/motor/proto
    cmds:
      - echo "Generating and Pushing Protobufs for Motor"
      - buf mod update
      - buf build
      - buf push

  buf:blockchain:
    dir: internal/blockchain/proto
    cmds:
      - echo "Generating and Pushing Protobufs for Blockchain"
      - buf mod update
      - buf build
      - buf push

  clean:
    cmds:
      - echo "Cleaning"
      - rm -rf ./build
      - rm -rf ./dist
      - rm -rf ./io.sonr.motor.aar
      - rm -rf ./sonr-motor.wasm
      - rm -rf ./SonrMotor.xcframework
      - rm -rf ./docs/.docusaurus/
      - rm -rf ./docs/build
      - go mod tidy

  docs:
    cmds:
      - echo "yarn docusaurus..."
      - yarn docusaurus
    silent: true
    dir: docs

  docs:start:
    cmds:
      - task: swag:build
      - echo "yarn start..."
      - yarn start
    silent: true
    dir: docs

  docs:build:
    cmds:
      - task: swag:build
      - echo "yarn build..."
      - yarn build
    silent: true
    dir: docs

  docs:swizzle:
    cmds:
      - echo "yarn swizzle..."
      - yarn swizzle
    silent: true
    dir: docs

  docs:deploy:
    cmds:
      - echo "yarn deploy..."
      - USE_SSH=true yarn deploy
    silent: true
    dir: docs

  docs:clear:
    cmds:
      - echo "yarn clear..."
      - yarn clear
    silent: true
    dir: docs

  docs:serve:
    cmds:
      - echo "yarn serve..."
      - yarn serve
    silent: true
    dir: docs

  proto:go:
    cmds:
      - echo "Generating Protobufs"
      - ignite generate proto-go
      - go mod tidy

  chain:serve:
    summary: Serve the blockchain using starport
    cmds:
      - ignite chain serve --reset-once
    silent: true

  release:
    cmds:
      - echo "Releasing all binaries..."
      - goreleaser release --skip-publish --snapshot --rm-dist --parallelism 4

  swag:build:
    cmds:
      - echo "Building swagger api docs for highway"
      - swag i -g internal/highway/http/server.go --output docs/static
      - mv docs/static/swagger.yaml docs/static/highway.yaml
      - rm -rf docs/static/swagger.json
      - echo "Building Open api docs for Blockchain"
      - ignite generate openapi
      - go mod tidy

