version: "3"
vars:
  ROOT_DIR:
    sh: pwd

includes:
  pkl:
    dir: ./third_party/pkl
    taskfile: ./third_party/pkl/Taskfile.yml

tasks:
  hway:assets:
    internal: true
    cmds:
      - go run github.com/syumai/workers/cmd/workers-assets-gen -mode=go -o ./cmd/gateway/build

  hway:build:
    dir: cmd/gateway
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - task: hway:assets
      - go build -o build/app.wasm main.go

  hway:dev:
    dir: cmd/gateway
    cmds:
      - task: nebula:build
      - bunx wrangler dev

  hway:deploy:
    dir: cmd/gateway
    cmds:
      - task: nebula:build
      - bunx wrangler deploy

  dwn:build:
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o build/app.wasm ./cmd/dwn/main.go

  nebula:build:
    dir: pkg/nebula
    cmds:
      - bun install
      - bun run deps.mjs
      - bunx tailwindcss -i ./global/styles/globals.css -o ./assets/css/styles.css
      - templ generate

  # ╭───────────────────────────────────────────────────────────╮
  # │                  Registration Components                  │
  # ╰───────────────────────────────────────────────────────────╯

  buf:push:
    cmds:
      - task: buf:push:sonr
      - task: buf:push:thirdparty

  buf:deps:
    cmds:
      - task: buf:deps:sonr
      - task: buf:deps:thirdparty

  buf:deps:sonr:
    internal: true
    dir: proto
    cmds:
      - buf dep update

  buf:deps:thirdparty:
    internal: true
    dir: third_party/proto
    cmds:
      - buf dep update

  buf:push:sonr:
    internal: true
    dir: proto
    cmds:
      - buf build
      - buf push

  buf:push:thirdparty:
    internal: true
    dir: third_party/proto
    cmds:
      - buf build
      - buf push
