version: "3"
vars:
  ROOT_DIR:
    sh: pwd

tasks:
  hway:assets:
    internal: true
    cmds:
      - go run github.com/syumai/workers/cmd/workers-assets-gen -mode=go -o ./cmd/gateway/build

  hway:build:
    dir: cmd/gateway
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - task: hway:assets
      - go build -o build/app.wasm main.go

  hway:dev:
    dir: cmd/gateway
    cmds:
      - task: nebula:build
      - bunx wrangler dev

  hway:deploy:
    dir: cmd/gateway
    cmds:
      - task: nebula:build
      - bunx wrangler deploy

  dwn:build:
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o build/app.wasm ./cmd/dwn/main.go

  nebula:build:
    dir: app/nebula
    cmds:
      - bun install
      - bun run deps.mjs
      - bunx tailwindcss -i ./global/styles/globals.css -o ./assets/css/styles.css
      - templ generate

  # ╭───────────────────────────────────────────────────────────╮
  # │                  Registration Components                  │
  # ╰───────────────────────────────────────────────────────────╯

  buf:push:
    cmds:
      - task: buf:push:sonr
      - task: buf:push:thirdparty

  buf:deps:
    cmds:
      - task: buf:deps:sonr
      - task: buf:deps:thirdparty

  buf:deps:sonr:
    internal: true
    dir: proto
    cmds:
      - buf dep update

  buf:deps:thirdparty:
    internal: true
    dir: third_party/proto
    cmds:
      - buf dep update

  buf:push:sonr:
    internal: true
    dir: proto
    cmds:
      - buf build
      - buf push

  buf:push:thirdparty:
    internal: true
    dir: third_party/proto
    cmds:
      - buf build
      - buf push

  # ╭───────────────────────────────────────────────────────────╮
  # │                  Registration Components                  │
  # ╰───────────────────────────────────────────────────────────╯

  pkl:build:
    cmds:
      - pkl project package packages/*/

  pkl:gen:
    sources:
      - third_party/pkl/packages/common.types/Ctx.pkl
      - third_party/pkl/packages/commmon.types/DWN.pkl
      - third_party/pkl/packages/common.types/ORM.pkl
    cmds:
      - for: sources
        cmd: go run github.com/apple/pkl-go/cmd/pkl-gen-go {{ .ITEM }}
