name: Default Todo
description: Break down feature requirements into tasks.
title: "Name of the new task"
labels: ["#TODO", "#OKR"]
assignees: ["prnk28"]
projects: ["onsonr/37"]
body:
  - type: textarea
    attributes:
      label: Description
      description: The expected deliverable of the task.
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Associated Files
      description: |
        These files will be modified by this task.
      value: |
        - [proto/did/v1/state.proto](https://github.com/onsonr/sonr/blob/develop/proto/did/v1/state.proto)
        - [proto/did/v1/tx.proto](https://github.com/onsonr/sonr/blob/develop/proto/did/v1/tx.proto)
    validations:
      required: false
  - type: textarea
    attributes:
      label: References
      description: |
        Use these documents to help you complete the task.
      value: |
        - [Cosmos ORM Docs](https://github.com/cosmos/orm)
        - [DID Document Spec](https://docs.cosmos.network)
    validations:
      required: false
