FROM scratch

LABEL org.opencontainers.image.title="Hway"
LABEL org.opencontainers.image.description="Highway is a high-performance, low-latency, and scalable gateway for secure access to the Sonr blockchain."
LABEL org.opencontainers.image.source="https://github.com/sonrhq/sonr"
LABEL org.opencontainers.image.licenses="OpenGL 3.0"
LABEL org.opencontainers.image.documentation="https://sonr.guide"
LABEL org.opencontainers.image.vendor="Sonr Inc."

ENTRYPOINT ["/hway"]
COPY hway /
