# sonrhq/chain: Earthfile
# ---------------------------------------------------------------------
VERSION 0.7
PROJECT sonrhq/testnet-1


# build
build:
    FROM tinygo/tinygo:0.30.0
    COPY . .
    RUN go run github.com/syumai/workers/cmd/workers-assets-gen@v0.23.1
    RUN tinygo build -o ./build/app.wasm -target wasm -no-debug ./...
    SAVE ARTIFACT build AS LOCAL build

# dev
dev:
    LOCALLY
    RUN wrangler dev

# deploy
deploy:
    LOCALLY
    RUN wrangler deploy
