VERSION 0.7
PROJECT sonrhq/rails


# build - builds the faucet binary
build:
    FROM node:18.7-alpine
    ARG cosmosjsVersion=0.28.11
    RUN npm install @cosmjs/faucet@$cosmosjsVersion --global --production
    WORKDIR /app
    COPY start.sh .
    EXPOSE 4500
    ENTRYPOINT ["sh", "start.sh"]
    SAVE IMAGE sonrhq/faucet:latest
