VERSION 0.7
FROM golang:1.21.5-alpine

# ---------------------------------------------------------------------

# deps - downloads dependencies
deps:
    RUN apk add --update --no-cache \
    bash \
    binutils \
    ca-certificates \
    coreutils \
    curl \
    findutils \
    g++ \
    git \
    grep \
    make \
    nodejs \
    npm \
    openssl \
    util-linux
    COPY go.mod go.sum ./
    RUN go mod download
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

# build - builds the flavored ipfs gateway
build:
    FROM matrixdotorg/dendrite-monolith:latest
    ARG serverName=matrix.sonr.run
    ARG psqlConnURI=postgres://postgres:pwd@postgres:5432/postgres?sslmode=disable
    RUN /usr/bin/generate-keys -private-key matrix_key.pem
    SAVE ARTIFACT matrix_key.pem AS LOCAL matrix_key.pem
    RUN /usr/bin/generate-config -server $serverName -db $psqlConnURI > dendrite.yaml
    SAVE ARTIFACT dendrite.yaml AS LOCAL dendrite.yaml

# run - runs the flavored ipfs gateway
run:
    LOCALLY
    ARG serverName=matrix.sonr.run
    SAVE IMAGE --push sonrhq/dendrite:latest
