version: "0.6"

processes:
  ipfs:
    namespace: devnet
    command: "devbox run ipfs"
    background: true
    availability:
      restart: never
      max_restarts: 0

  sonr:
    namespace: devnet
    background: true
    command: "devbox run sonr"
    restart: never
    max_restarts: 1
    depends:
      - ipfs

  hway:
    namespace: devnet
    background: true
    command: "devbox run hway"
    restart: never
    max_restarts: 1
    depends:
      - ipfs
      - sonr
