version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "devbox run ipfs"
    background: true
    availability:
      restart: never
      max_restarts: 0

  sonr:
    namespace: testnet
    background: true
    command: "devbox run devnet"
    restart: never
    max_restarts: 1
    depends:
      - ipfs

  hway-air:
    namespace: testnet
    background: true
    command: "devbox run air"
    restart: never
    max_restarts: 1
    depends:
      - sonr
