version: "0.6"

processes:
  sonr:
    namespace: devnet
    command: "make sh-testnet"
    max_restarts: 1

  hway:
    namespace: devnet
    command: "./build/hway"
    max_restarts: 1
    depends:
      - sonr
