# sonr/cmd: Earthfile
# ---------------------------------------------------------------------
VERSION 0.7
PROJECT sonrhq/testnet-1
IMPORT ../ AS root
FROM golang:1.21-alpine3.18
RUN apk add --update --no-cache \
    bash \
    binutils \
    ca-certificates \
    coreutils \
    curl \
    findutils \
    g++ \
    git \
    grep \
    make \
    openssl \
    util-linux
# ---------------------------------------------------------------------

# init - Creates base config and keys
init:
    WORKDIR /root
    ARG chainId=sonr-testnet-1
    ARG enableSwagger=true
    ARG enableAPI=true
    ARG faucetBalance=1000000snr
    ARG genesisBalance=10000000snr
    ARG keyringBackend=test
    ARG moniker=austin
    ARG vestingAmount=1000000snr
    COPY root+build/sonrd .
    RUN ./sonrd config set client chain-id $chainId
    RUN ./sonrd config set client keyring-backend $keyringBackend
    RUN ./sonrd config set app api.enable $enableAPI
    RUN ./sonrd config set app api.swagger $enableSwagger
    RUN ./sonrd keys add alice
    RUN ./sonrd keys add bob

    RUN ./sonrd init $moniker --chain-id $chainId --default-denom snr
    RUN ./sonrd genesis add-genesis-account alice $genesisBalance
    RUN ./sonrd genesis add-genesis-account bob $faucetBalance
    RUN ./sonrd genesis gentx alice $vestingAmount --chain-id $chainId
    RUN ./sonrd genesis collect-gentxs
    SAVE ARTIFACT /root/.sonr AS LOCAL data


# runner - Creates a containerized node with preconfigured keys
runner:
    FROM root+docker
    ARG --secret --required infisicalToken
    ARG --required mountVolume

    ENV INFISICAL_TOKEN=$infisicalToken
    VOLUME $mountVolume:/root/.sonr

    RUN apt-get update && apt-get install -y bash curl && curl -1sLf \
    'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash \
    && apt-get update && apt-get install -y infisical

    COPY root+scripts/src/inf-sonr.sh .
    RUN infisical run --command "sh inf-sonr.sh"

    EXPOSE 26657
    EXPOSE 1317
    EXPOSE 26656
    EXPOSE 9090

    CMD ["sonrd start"]
    SAVE IMAGE --push sonrhq/sonrd:$tag-runner ghcr.io/sonrhq/sonrd:$tag-runner sonr-runner:$tag
