ARG GO_VERSION="1.19"
ARG RUNNER_IMAGE="alpine:3.16"


# ! ||----------------------------------------------------------------------------------||
# ! ||                               Sonr Standalone Node                               ||
# ! ||----------------------------------------------------------------------------------||
FROM --platform=linux alpine

LABEL org.opencontainers.image.source https://github.com/sonrhq/core
LABEL org.opencontainers.image.description "Base sonr daemon image"
# Copy sonrd binary and config
COPY ../bin/sonrd /usr/local/bin/sonrd
COPY start.sh start.sh
COPY sonr.yml sonr.yml
ENV SONR_LAUNCH_CONFIG=/sonr.yml

# Expose ports
EXPOSE 26657
EXPOSE 1317
EXPOSE 26656
EXPOSE 8080
EXPOSE 9090

