VERSION 0.7
PROJECT sonrhq/rails


# builds - builds the postgres binary
build:
    FROM postgres:15-alpine
    ARG password=pwd
    COPY ./schema.sql /docker-entrypoint-initdb.d/
    SAVE IMAGE sonrhq/postgres:15

