// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core/domain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
// It holds all the parameters of this module.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetUsernameRecordsRequest is the request type for the
// Query/UsernameRecord RPC method. It contains the index of the UsernameRecords
// to be queried.
type QueryGetUsernameRecordsRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetUsernameRecordsRequest) Reset()         { *m = QueryGetUsernameRecordsRequest{} }
func (m *QueryGetUsernameRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUsernameRecordsRequest) ProtoMessage()    {}
func (*QueryGetUsernameRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{2}
}
func (m *QueryGetUsernameRecordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUsernameRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUsernameRecordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUsernameRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUsernameRecordsRequest.Merge(m, src)
}
func (m *QueryGetUsernameRecordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUsernameRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUsernameRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUsernameRecordsRequest proto.InternalMessageInfo

func (m *QueryGetUsernameRecordsRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetUsernameRecordsResponse is the response type for the
// Query/UsernameRecord RPC method. It contains the queried UsernameRecords.
type QueryGetUsernameRecordsResponse struct {
	UsernameRecords UsernameRecord `protobuf:"bytes,1,opt,name=usernameRecords,proto3" json:"usernameRecords"`
}

func (m *QueryGetUsernameRecordsResponse) Reset()         { *m = QueryGetUsernameRecordsResponse{} }
func (m *QueryGetUsernameRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUsernameRecordsResponse) ProtoMessage()    {}
func (*QueryGetUsernameRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{3}
}
func (m *QueryGetUsernameRecordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUsernameRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUsernameRecordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUsernameRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUsernameRecordsResponse.Merge(m, src)
}
func (m *QueryGetUsernameRecordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUsernameRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUsernameRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUsernameRecordsResponse proto.InternalMessageInfo

func (m *QueryGetUsernameRecordsResponse) GetUsernameRecords() UsernameRecord {
	if m != nil {
		return m.UsernameRecords
	}
	return UsernameRecord{}
}

// QueryAllUsernameRecordsRequest is the request type for the
// Query/UsernameRecordAll RPC method. It contains the pagination information
// for the query.
type QueryAllUsernameRecordsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUsernameRecordsRequest) Reset()         { *m = QueryAllUsernameRecordsRequest{} }
func (m *QueryAllUsernameRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllUsernameRecordsRequest) ProtoMessage()    {}
func (*QueryAllUsernameRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{4}
}
func (m *QueryAllUsernameRecordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUsernameRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUsernameRecordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUsernameRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUsernameRecordsRequest.Merge(m, src)
}
func (m *QueryAllUsernameRecordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUsernameRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUsernameRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUsernameRecordsRequest proto.InternalMessageInfo

func (m *QueryAllUsernameRecordsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllUsernameRecordsResponse is the response type for the
// Query/UsernameRecordAll RPC method. It contains all queried UsernameRecords
// and the pagination information.
type QueryAllUsernameRecordsResponse struct {
	UsernameRecords []UsernameRecord    `protobuf:"bytes,1,rep,name=usernameRecords,proto3" json:"usernameRecords"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUsernameRecordsResponse) Reset()         { *m = QueryAllUsernameRecordsResponse{} }
func (m *QueryAllUsernameRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllUsernameRecordsResponse) ProtoMessage()    {}
func (*QueryAllUsernameRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7084fe185c90ac, []int{5}
}
func (m *QueryAllUsernameRecordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUsernameRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUsernameRecordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUsernameRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUsernameRecordsResponse.Merge(m, src)
}
func (m *QueryAllUsernameRecordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUsernameRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUsernameRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUsernameRecordsResponse proto.InternalMessageInfo

func (m *QueryAllUsernameRecordsResponse) GetUsernameRecords() []UsernameRecord {
	if m != nil {
		return m.UsernameRecords
	}
	return nil
}

func (m *QueryAllUsernameRecordsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "core.domain.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "core.domain.QueryParamsResponse")
	proto.RegisterType((*QueryGetUsernameRecordsRequest)(nil), "core.domain.QueryGetUsernameRecordsRequest")
	proto.RegisterType((*QueryGetUsernameRecordsResponse)(nil), "core.domain.QueryGetUsernameRecordsResponse")
	proto.RegisterType((*QueryAllUsernameRecordsRequest)(nil), "core.domain.QueryAllUsernameRecordsRequest")
	proto.RegisterType((*QueryAllUsernameRecordsResponse)(nil), "core.domain.QueryAllUsernameRecordsResponse")
}

func init() { proto.RegisterFile("core/domain/query.proto", fileDescriptor_8b7084fe185c90ac) }

var fileDescriptor_8b7084fe185c90ac = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0xad, 0x0d, 0x38, 0x05, 0xc5, 0x49, 0x4a, 0x4b, 0x6a, 0x37, 0x65, 0xc0, 0x2a,
	0xfe, 0x98, 0x21, 0x15, 0x3c, 0xdb, 0x1e, 0xac, 0xe0, 0xa5, 0x2e, 0x78, 0xf1, 0x36, 0x49, 0x86,
	0xcd, 0xc2, 0xee, 0xbc, 0xed, 0xcc, 0x44, 0x5a, 0xc4, 0x8b, 0x77, 0x41, 0x14, 0xfc, 0x57, 0xfc,
	0x17, 0x7a, 0x0c, 0x78, 0xf1, 0x24, 0x92, 0xf8, 0x87, 0x48, 0x66, 0x26, 0x98, 0x31, 0xbb, 0x2a,
	0x9e, 0x32, 0x99, 0xf7, 0x7d, 0xdf, 0xf7, 0x79, 0xf3, 0x5e, 0x82, 0xb6, 0x07, 0xa0, 0x04, 0x1b,
	0x42, 0xc1, 0x33, 0xc9, 0xce, 0xc6, 0x42, 0x5d, 0xd0, 0x52, 0x81, 0x01, 0xbc, 0x39, 0x0f, 0x50,
	0x17, 0xe8, 0xec, 0x2c, 0xab, 0x4a, 0xae, 0x78, 0xa1, 0x9d, 0x2c, 0x8c, 0x28, 0x31, 0x00, 0x35,
	0xf4, 0x91, 0xbb, 0x03, 0xd0, 0x05, 0x68, 0xd6, 0xe7, 0x5a, 0x38, 0x67, 0xf6, 0xaa, 0xd7, 0x17,
	0x86, 0xf7, 0x58, 0xc9, 0xd3, 0x4c, 0x72, 0x93, 0x81, 0xf4, 0xda, 0x76, 0x0a, 0x29, 0xd8, 0x23,
	0x9b, 0x9f, 0xfc, 0xed, 0xcd, 0x14, 0x20, 0xcd, 0x05, 0xe3, 0x65, 0xc6, 0xb8, 0x94, 0x60, 0x6c,
	0x8a, 0xaf, 0x4c, 0xda, 0x08, 0x3f, 0x9f, 0xbb, 0x9e, 0x5a, 0x9c, 0x44, 0x9c, 0x8d, 0x85, 0x36,
	0xe4, 0x29, 0x6a, 0x05, 0xb7, 0xba, 0x04, 0xa9, 0x05, 0xee, 0xa1, 0xa6, 0xc3, 0xde, 0x89, 0xf6,
	0xa3, 0x3b, 0x9b, 0x87, 0x2d, 0xba, 0xd4, 0x1e, 0x75, 0xe2, 0xe3, 0x2b, 0x97, 0xdf, 0xba, 0x8d,
	0xc4, 0x0b, 0xc9, 0x23, 0x14, 0x5b, 0xa7, 0x13, 0x61, 0x5e, 0x68, 0xa1, 0x24, 0x2f, 0x44, 0x62,
	0xfb, 0x5b, 0xd4, 0xc2, 0x6d, 0xb4, 0x91, 0xc9, 0xa1, 0x38, 0xb7, 0x9e, 0x57, 0x13, 0xf7, 0x85,
	0x48, 0xd4, 0xad, 0xcd, 0xf3, 0x34, 0xcf, 0xd0, 0xf5, 0x71, 0x18, 0xf2, 0x58, 0xbb, 0x01, 0x56,
	0x98, 0xee, 0xf1, 0x7e, 0xcf, 0x24, 0x23, 0xcf, 0x79, 0x94, 0xe7, 0x35, 0x9c, 0x4f, 0x10, 0xfa,
	0xf5, 0xe2, 0xbe, 0xd2, 0x01, 0x75, 0xe3, 0xa1, 0xf3, 0xf1, 0x50, 0x37, 0x78, 0x3f, 0x1e, 0x7a,
	0xca, 0x53, 0xe1, 0x73, 0x93, 0xa5, 0x4c, 0xf2, 0x39, 0xf2, 0xad, 0x55, 0x95, 0xfa, 0x53, 0x6b,
	0xeb, 0xff, 0xd7, 0x1a, 0x3e, 0x09, 0xc0, 0xd7, 0x2c, 0xf8, 0xed, 0xbf, 0x82, 0x3b, 0x92, 0x65,
	0xf2, 0xc3, 0x4f, 0xeb, 0x68, 0xc3, 0x92, 0xe3, 0x11, 0x6a, 0xba, 0x69, 0xe3, 0x6e, 0x00, 0xb4,
	0xba, 0x4a, 0x9d, 0xfd, 0x7a, 0x81, 0x2b, 0x41, 0x76, 0xdf, 0x7e, 0xf9, 0xf1, 0x71, 0x6d, 0x0b,
	0xb7, 0xd8, 0xea, 0xef, 0x03, 0x7f, 0x88, 0xd0, 0xb5, 0xb0, 0x4d, 0x7c, 0x6f, 0xd5, 0xb1, 0x76,
	0xbb, 0x3a, 0xf7, 0xff, 0x4d, 0xec, 0x51, 0x6e, 0x59, 0x94, 0x2e, 0xde, 0x0b, 0x50, 0x16, 0x0f,
	0xca, 0x5e, 0xdb, 0xdd, 0x7c, 0x83, 0xdf, 0x45, 0xe8, 0x46, 0x68, 0x71, 0x94, 0xe7, 0x55, 0x5c,
	0xb5, 0xdb, 0x54, 0xc5, 0x55, 0xbf, 0x0f, 0x64, 0xcf, 0x72, 0x6d, 0xe3, 0xad, 0x4a, 0xae, 0xe3,
	0xc7, 0x97, 0xd3, 0x38, 0x9a, 0x4c, 0xe3, 0xe8, 0xfb, 0x34, 0x8e, 0xde, 0xcf, 0xe2, 0xc6, 0x64,
	0x16, 0x37, 0xbe, 0xce, 0xe2, 0xc6, 0xcb, 0x83, 0x34, 0x33, 0xa3, 0x71, 0x9f, 0x0e, 0xa0, 0x60,
	0x1a, 0xa4, 0x7a, 0x90, 0x81, 0xfd, 0x64, 0xe7, 0x0b, 0x13, 0x73, 0x51, 0x0a, 0xdd, 0x6f, 0xda,
	0x7f, 0x83, 0x87, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x02, 0x4c, 0xea, 0xc9, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	// It returns the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// UsernameRecord queries a list of UsernameRecords items by index.
	// It returns a list of UsernameRecords items.
	UsernameRecord(ctx context.Context, in *QueryGetUsernameRecordsRequest, opts ...grpc.CallOption) (*QueryGetUsernameRecordsResponse, error)
	// UsernameRecordAll queries all UsernameRecords items.
	// It returns all UsernameRecords items.
	UsernameRecordAll(ctx context.Context, in *QueryAllUsernameRecordsRequest, opts ...grpc.CallOption) (*QueryAllUsernameRecordsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/core.domain.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UsernameRecord(ctx context.Context, in *QueryGetUsernameRecordsRequest, opts ...grpc.CallOption) (*QueryGetUsernameRecordsResponse, error) {
	out := new(QueryGetUsernameRecordsResponse)
	err := c.cc.Invoke(ctx, "/core.domain.Query/UsernameRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UsernameRecordAll(ctx context.Context, in *QueryAllUsernameRecordsRequest, opts ...grpc.CallOption) (*QueryAllUsernameRecordsResponse, error) {
	out := new(QueryAllUsernameRecordsResponse)
	err := c.cc.Invoke(ctx, "/core.domain.Query/UsernameRecordAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of the module.
	// It returns the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// UsernameRecord queries a list of UsernameRecords items by index.
	// It returns a list of UsernameRecords items.
	UsernameRecord(context.Context, *QueryGetUsernameRecordsRequest) (*QueryGetUsernameRecordsResponse, error)
	// UsernameRecordAll queries all UsernameRecords items.
	// It returns all UsernameRecords items.
	UsernameRecordAll(context.Context, *QueryAllUsernameRecordsRequest) (*QueryAllUsernameRecordsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) UsernameRecord(ctx context.Context, req *QueryGetUsernameRecordsRequest) (*QueryGetUsernameRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameRecord not implemented")
}
func (*UnimplementedQueryServer) UsernameRecordAll(ctx context.Context, req *QueryAllUsernameRecordsRequest) (*QueryAllUsernameRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameRecordAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.domain.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UsernameRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUsernameRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UsernameRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.domain.Query/UsernameRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UsernameRecord(ctx, req.(*QueryGetUsernameRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UsernameRecordAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUsernameRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UsernameRecordAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.domain.Query/UsernameRecordAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UsernameRecordAll(ctx, req.(*QueryAllUsernameRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.domain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "UsernameRecord",
			Handler:    _Query_UsernameRecord_Handler,
		},
		{
			MethodName: "UsernameRecordAll",
			Handler:    _Query_UsernameRecordAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/domain/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetUsernameRecordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUsernameRecordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUsernameRecordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUsernameRecordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUsernameRecordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUsernameRecordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.UsernameRecords.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllUsernameRecordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUsernameRecordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUsernameRecordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllUsernameRecordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUsernameRecordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUsernameRecordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UsernameRecords) > 0 {
		for iNdEx := len(m.UsernameRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UsernameRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetUsernameRecordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUsernameRecordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.UsernameRecords.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllUsernameRecordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllUsernameRecordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UsernameRecords) > 0 {
		for _, e := range m.UsernameRecords {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUsernameRecordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUsernameRecordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUsernameRecordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUsernameRecordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUsernameRecordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUsernameRecordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsernameRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UsernameRecords.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUsernameRecordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUsernameRecordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUsernameRecordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUsernameRecordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUsernameRecordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUsernameRecordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsernameRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UsernameRecords = append(m.UsernameRecords, UsernameRecord{})
			if err := m.UsernameRecords[len(m.UsernameRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
